const constants = {
  NAVIGATEHOME: "/",
  NAVIGATEDISCOVER: "/discover",
  NAVIGATEGAMEFOLIO: "/gamefolio",
  NAVIGATELANDING: "/landing",
  NAVIGATESIGNUP: "/signup",
  NAVIGATELOGIN: "/login",
  NAVIGATESIGNIN: "/signin",
  NAVIGATECHOOSEPASSWORD: "/choosepassword",
  NAVIGATERESETPASSWORD: "/resetpassword",
  NAVIGATENEWPASSWORD: "/newpassword",
  NAVIGATESENDOTP: "/sendotp",
  NAVIGATEVERIFYEMAIL: "/verifyemail",
  NAVIGATEPOST: "post",
  NAVIGATEADDPOST: "/add-post",
  NAVIGATEGAMEDETAIL: "/game-detail",
  NAVIGATEONBOARDING: "/onboarding",
  NAVIGATEPROFILE: "/profile",
  NAVIGATEBANNED: "/banned",
  NAVIGATEFOLLOWERS: "/followers",
  NAVIGATECONFIRMATION: "/confirmation",
  NAVIGATEREUPLOADPROFILE: "/uploadprofile",
  NAVIGATETHEME: "/theme",
  NAVIGATEWALLET: "/wallet",
  NAVIGATEDRAFT: "/draft",
  NAVIGATESETTINGS: "/settings",
  NAVIGATELOGOUT: "/logout",
};

export default constants;
